[memcache] autoconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -739,8 +739,12 @@ SNMP_LIBS
 SNMP_CPPFLAGS
 SERVER_LDFLAGS
 SERVER_LIBS
+MEMCACHE_CFLAGS
+MEMCACHE_LIBS
 JABBER_TRUE
 JABBER_FALSE
+MEMCACHE_TRUE
+MEMCACHE_FALSE
 LDAP_CPPFLAGS
 LDAP_LDFLAGS
 RANLIB
@@ -758,7 +762,9 @@ CPPFLAGS
 CPP
 PKG_CONFIG
 IKSEMEL_CFLAGS
-IKSEMEL_LIBS'
+IKSEMEL_LIBS
+MEMCACHE_CFLAGS
+MEMCACHE_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1343,6 +1349,7 @@ Optional Features:
   --enable-server         Turn on build of server
   --enable-agent          Turn on build of agent
   --enable-ipv6         Turn on support of IPv6
+  --enable-memcache      Build with memcached support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1396,6 +1403,10 @@ Some influential environment variables:
               C compiler flags for IKSEMEL, overriding pkg-config
   IKSEMEL_LIBS
               linker flags for IKSEMEL, overriding pkg-config
+  MEMCACHE_CFLAGS
+              C compiler flags for MEMCACHE, overriding pkg-config
+  MEMCACHE_LIBS
+              linker flags for MEMCACHE, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -11395,6 +11406,133 @@ echo "$as_me: error: You can configure for only one SNMP library." >&2;}
 
 
 
+	# Check whether --enable-memcache was given.
+if test "${enable_memcache+set}" = set; then
+  enableval=$enable_memcache; enable_memcache="${enableval}"
+else
+  enable_memcache=no
+fi
+
+	if test "x$enable_memcache" = "xyes"; then
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for MEMCACHE" >&5
+echo $ECHO_N "checking for MEMCACHE... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$MEMCACHE_CFLAGS"; then
+        pkg_cv_MEMCACHE_CFLAGS="$MEMCACHE_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libmemcached >= 0.8.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libmemcached >= 0.8.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_MEMCACHE_CFLAGS=`$PKG_CONFIG --cflags "libmemcached >= 0.8.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$MEMCACHE_LIBS"; then
+        pkg_cv_MEMCACHE_LIBS="$MEMCACHE_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libmemcached >= 0.8.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libmemcached >= 0.8.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_MEMCACHE_LIBS=`$PKG_CONFIG --libs "libmemcached >= 0.8.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        MEMCACHE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libmemcached >= 0.8.0"`
+        else
+	        MEMCACHE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libmemcached >= 0.8.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$MEMCACHE_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (libmemcached >= 0.8.0) were not met:
+
+$MEMCACHE_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables MEMCACHE_CFLAGS
+and MEMCACHE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (libmemcached >= 0.8.0) were not met:
+
+$MEMCACHE_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables MEMCACHE_CFLAGS
+and MEMCACHE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables MEMCACHE_CFLAGS
+and MEMCACHE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables MEMCACHE_CFLAGS
+and MEMCACHE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	MEMCACHE_CFLAGS=$pkg_cv_MEMCACHE_CFLAGS
+	MEMCACHE_LIBS=$pkg_cv_MEMCACHE_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MEMCACHE 1
+_ACEOF
+
+	fi
+	CFLAGS="${CFLAGS} ${MEMCACHE_CFLAGS}"
+	SERVER_LDFLAGS="${SERVER_LDFLAGS} ${MEMCACHE_LIBS}"
 fi
 
 
@@ -11405,6 +11543,16 @@ if test "x$found_jabber" = "xyes"; then
 else
   JABBER_TRUE='#'
   JABBER_FALSE=
+fi
+
+
+
+if test "x$enable_memcache" = "xyes"; then
+  MEMCACHE_TRUE=
+  MEMCACHE_FALSE='#'
+else
+  MEMCACHE_TRUE='#'
+  MEMCACHE_FALSE=
 fi
 
 
@@ -12026,6 +12174,13 @@ if test -z "${JABBER_TRUE}" && test -z "${JABBER_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"JABBER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"JABBER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MEMCACHE_TRUE}" && test -z "${MEMCACHE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MEMCACHE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MEMCACHE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12775,8 +12930,12 @@ SNMP_LIBS!$SNMP_LIBS$ac_delim
 SNMP_CPPFLAGS!$SNMP_CPPFLAGS$ac_delim
 SERVER_LDFLAGS!$SERVER_LDFLAGS$ac_delim
 SERVER_LIBS!$SERVER_LIBS$ac_delim
+MEMCACHE_CFLAGS!$MEMCACHE_CFLAGS$ac_delim
+MEMCACHE_LIBS!$MEMCACHE_LIBS$ac_delim
 JABBER_TRUE!$JABBER_TRUE$ac_delim
 JABBER_FALSE!$JABBER_FALSE$ac_delim
+MEMCACHE_TRUE!$MEMCACHE_TRUE$ac_delim
+MEMCACHE_FALSE!$MEMCACHE_FALSE$ac_delim
 LDAP_CPPFLAGS!$LDAP_CPPFLAGS$ac_delim
 LDAP_LDFLAGS!$LDAP_LDFLAGS$ac_delim
 RANLIB!$RANLIB$ac_delim
@@ -12784,7 +12943,7 @@ ARCH!$ARCH$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
